version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: ghost-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf/ghost.conf:/etc/nginx/conf.d/ghost.conf:z
    networks:
      - nginx
    restart: always

  ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    volumes:
      - ./ghost/volumes/config.production.json:/var/lib/ghost/config.production.json #overwrite default settings 
      - ./ghost/content:/var/lib/ghost/content:z
    expose:
    - "3306"
    environment: # this section can be commented to start in dev mode by default
      - NODE_ENV=production # set either production or development, then it will load the respective config
    networks:
      - nginx
      - ghost
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./dbdata:/var/lib/mysql:z  # Persist storage
    expose:
      - "3306"
    environment:
      # Beware of special characters in password that can be interpreted by shell
      - MYSQL_ROOT_PASSWORD=root #specify your root pass
      - MYSQL_DATABASE=ghostdata
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost #please change this
    networks:
      - ghost
    restart: always

networks:
  nginx: {}
  ghost: {}
